# Generated by Django 2.0.4 on 2018-06-19 14:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', help_text='图表标题', max_length=20, verbose_name='图表标题')),
                ('desc', models.CharField(default='', help_text='图表描述', max_length=20, verbose_name='图表描述')),
                ('x_axis', models.CharField(default='', help_text='维度', max_length=100, verbose_name='维度')),
                ('y_axis', models.CharField(default='', help_text='数值', max_length=100, verbose_name='数值')),
                ('chart_type', models.IntegerField(default=0, help_text='表格类别总览', max_length=10, verbose_name='表格类别总览')),
                ('step1', models.CharField(default='', max_length=100, verbose_name='json源文件名')),
                ('step2', models.CharField(default='', max_length=100, verbose_name='csv源文件名')),
                ('step3', models.CharField(default='', max_length=100, verbose_name='预处理源文件')),
                ('step4', models.CharField(default='', max_length=100, verbose_name='数据挖掘源文件')),
                ('step5', models.CharField(default='', max_length=100, verbose_name='发布任务源文件')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '数据源',
                'verbose_name_plural': '数据源',
            },
        ),
        migrations.CreateModel(
            name='TaskInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(blank=True, help_text='任务名', max_length=30, null=True, verbose_name='任务名')),
                ('data_num', models.IntegerField(default=0, max_length=10, verbose_name='数据文件数量')),
                ('status_type', models.IntegerField(choices=[(0, '已删除'), (1, '已完成'), (2, '未完成')], default=2, help_text='任务状态', verbose_name='任务状态')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('task_desc', models.CharField(blank=True, default='', help_text='任务描述', max_length=120, null=True, verbose_name='任务描述')),
                ('task_home', models.CharField(default='D', max_length=2, verbose_name='任务存放盘')),
                ('task_folder', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='任务存放文件夹路径')),
            ],
            options={
                'verbose_name': '任务信息',
                'verbose_name_plural': '任务信息',
            },
        ),
    ]
