# Generated by Django 2.0.4 on 2018-05-30 01:40

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DataSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='TaskInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(blank=True, max_length=30, null=True, verbose_name='任务名')),
                ('data_num', models.IntegerField(default=1, max_length=10, verbose_name='数据文件数量')),
                ('state_type', models.IntegerField(choices=[(0, '已删除'), (1, '已完成'), (2, '未完成')], default=2, help_text='任务状态', verbose_name='任务状态')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户ID')),
            ],
            options={
                'verbose_name': '任务信息',
                'verbose_name_plural': '任务信息',
            },
        ),
        migrations.AddField(
            model_name='dataset',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.TaskInfo', verbose_name='任务信息'),
        ),
    ]
