# Generated by Django 2.0.4 on 2018-06-12 12:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dataset',
            options={'verbose_name': '数据源', 'verbose_name_plural': '数据源'},
        ),
        migrations.AddField(
            model_name='dataset',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间'),
        ),
        migrations.AddField(
            model_name='dataset',
            name='step1',
            field=models.CharField(default='', max_length=100, verbose_name='json源文件'),
        ),
        migrations.AddField(
            model_name='dataset',
            name='step2',
            field=models.CharField(default='', max_length=100, verbose_name='csv源文件'),
        ),
        migrations.AddField(
            model_name='dataset',
            name='step3',
            field=models.CharField(default='', max_length=100, verbose_name='预处理源文件'),
        ),
        migrations.AddField(
            model_name='dataset',
            name='step4',
            field=models.CharField(default='', max_length=100, verbose_name='数据挖掘源文件'),
        ),
        migrations.AddField(
            model_name='dataset',
            name='step5',
            field=models.CharField(default='', max_length=100, verbose_name='发布任务源文件'),
        ),
        migrations.AddField(
            model_name='taskinfo',
            name='task_folder',
            field=models.CharField(default='', max_length=50, verbose_name='任务存放文件夹路径名'),
        ),
        migrations.AddField(
            model_name='taskinfo',
            name='task_home',
            field=models.CharField(default='D', max_length=2, verbose_name='任务存放盘'),
        ),
    ]
