# Generated by Django 2.0.4 on 2018-09-11 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_auto_20180911_1400'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chart',
            old_name='data',
            new_name='data_set',
        ),
    ]
