# Generated by Django 2.0.4 on 2018-09-20 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_auto_20180908_0446'),
    ]

    operations = [
        migrations.AddField(
            model_name='chart',
            name='chart_folder',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='图表存放路径'),
        ),
        migrations.AlterField(
            model_name='chart',
            name='contrast_axis',
            field=models.CharField(blank=True, default='', help_text='图表对比轴', max_length=200, null=True, verbose_name='对比'),
        ),
        migrations.AlterField(
            model_name='chart',
            name='data_set',
            field=models.IntegerField(default=-1, verbose_name='数据集ID'),
        ),
        migrations.AlterField(
            model_name='chart',
            name='desc',
            field=models.CharField(blank=True, default='', help_text='图表描述', max_length=20, null=True, verbose_name='图表描述'),
        ),
        migrations.AlterField(
            model_name='chart',
            name='secondary_axis',
            field=models.CharField(blank=True, default='', help_text='图表次轴', max_length=200, null=True, verbose_name='次轴'),
        ),
        migrations.AlterField(
            model_name='chart',
            name='x_axis',
            field=models.CharField(blank=True, default='', help_text='图表维度', max_length=200, null=True, verbose_name='维度'),
        ),
        migrations.AlterField(
            model_name='chart',
            name='y_axis',
            field=models.CharField(blank=True, default='', help_text='图表数值', max_length=200, null=True, verbose_name='数值'),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='desc',
            field=models.CharField(default='', help_text='数据集描述描述', max_length=20, verbose_name='数据集描述信息'),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='title',
            field=models.CharField(default='', help_text='标题', max_length=20, verbose_name='数据集文件名'),
        ),
    ]
