# Generated by Django 2.0.4 on 2018-06-14 08:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tasks', '0006_auto_20180613_1303'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataset',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户ID'),
        ),
        migrations.AlterField(
            model_name='taskinfo',
            name='task_folder',
            field=models.CharField(default='', max_length=50, verbose_name='任务存放文件夹路径'),
        ),
    ]
