# Generated by Django 2.0.4 on 2018-06-19 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0008_remove_dataset_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskinfo',
            name='data_num',
            field=models.IntegerField(default=0, max_length=10, verbose_name='数据文件数量'),
        ),
        migrations.AlterField(
            model_name='taskinfo',
            name='task_folder',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='任务存放文件夹路径'),
        ),
    ]
