# Generated by Django 2.0.4 on 2018-09-20 02:52

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', help_text='类别名', max_length=30, verbose_name='类别名')),
                ('code', models.CharField(default='', help_text='类别code', max_length=30, verbose_name='类别code')),
                ('desc', models.TextField(blank=True, default='', help_text='类别描述', null=True, verbose_name='类别描述')),
                ('category_type', models.IntegerField(choices=[(1, '一级类目'), (2, '二级类目')], help_text='类目级别', verbose_name='类目级别')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('parent_category', models.ForeignKey(blank=True, help_text='父目录', null=True, on_delete=True, related_name='sub_cat', to='data_mining.ModelCategory', verbose_name='父类目级别')),
            ],
            options={
                'verbose_name': '模型类别',
                'verbose_name_plural': '模型类别',
            },
        ),
        migrations.CreateModel(
            name='Regression',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_set', models.IntegerField(default=0, verbose_name='数据集ID')),
                ('title', models.CharField(default='', help_text='标题', max_length=20, verbose_name='标题')),
                ('desc', models.CharField(blank=True, default='', help_text='描述', max_length=20, null=True, verbose_name='描述')),
                ('x_axis', models.CharField(blank=True, default='', help_text='特征项个数区分一元或多元', max_length=200, null=True, verbose_name='自变量')),
                ('y_axis', models.CharField(blank=True, default='', help_text='目标项', max_length=200, null=True, verbose_name='因变量')),
                ('division_ratio', models.FloatField(default=0, verbose_name='数据划分比例')),
                ('mth_power', models.IntegerField(default=1, verbose_name='次数m')),
                ('error_type', models.IntegerField(choices=[(1, 'MSE:均方误差'), (2, 'MAE:平均绝对误差'), (3, 'RMSE:均方根误差')], help_text='默认MSE', verbose_name='误差计算类别')),
                ('chart_folder1', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='图表存放路径1')),
                ('chart_folder2', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='图表存放路径2')),
                ('chart_folder3', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='图表存放路径3')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('updated_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='更新时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户ID')),
            ],
            options={
                'verbose_name': '数据图表',
                'verbose_name_plural': '数据图表',
            },
        ),
    ]
