# Generated by Django 2.0 on 2018-11-15 10:44

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clustering',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_set', models.IntegerField(default=-1, verbose_name='数据集ID')),
                ('title', models.CharField(default='', help_text='标题', max_length=20, verbose_name='标题')),
                ('desc', models.CharField(blank=True, default='', help_text='描述', max_length=20, null=True, verbose_name='描述')),
                ('k_clustering', models.IntegerField(default=8, verbose_name='k值')),
                ('Datacsv_list', models.CharField(default=10, max_length=20, verbose_name='传进的csv数值列')),
                ('random_state', models.IntegerField(default=30, verbose_name='随机种子值')),
                ('max_iter', models.IntegerField(default=300, verbose_name='最大迭代次数')),
                ('batch_size', models.IntegerField(default=100, verbose_name='随机取样数')),
                ('n_init', models.IntegerField(default=10, verbose_name='初始簇中心迭代次数')),
                ('reassignment_ratio', models.FloatField(default=0.01, verbose_name='质心重新赋值最大次数比例')),
                ('chart_folder1', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='图表存放路径1')),
                ('chart_folder2', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='图表存放路径2')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('updated_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '聚类分析模型',
                'verbose_name_plural': '聚类分析模型',
            },
        ),
        migrations.CreateModel(
            name='ModelCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', help_text='类别名', max_length=30, verbose_name='类别名')),
                ('code', models.CharField(default='', help_text='类别code', max_length=30, verbose_name='类别code')),
                ('desc', models.TextField(blank=True, default='', help_text='类别描述', null=True, verbose_name='类别描述')),
                ('category_type', models.IntegerField(choices=[(1, '一级类目'), (2, '二级类目')], help_text='类目级别', verbose_name='类目级别')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '模型类别',
                'verbose_name_plural': '模型类别',
            },
        ),
        migrations.CreateModel(
            name='Regression',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_set', models.IntegerField(default=-1, verbose_name='数据集ID')),
                ('title', models.CharField(default='', help_text='标题', max_length=20, verbose_name='标题')),
                ('desc', models.CharField(blank=True, default='', help_text='描述', max_length=20, null=True, verbose_name='描述')),
                ('x_axis', models.CharField(blank=True, default='', help_text='特征项个数区分一元或多元', max_length=200, null=True, verbose_name='自变量')),
                ('y_axis', models.CharField(blank=True, default='', help_text='目标项', max_length=200, null=True, verbose_name='因变量')),
                ('test_size', models.FloatField(default=0, verbose_name='数据划分比例')),
                ('xlabel', models.CharField(default='', help_text='X轴标签', max_length=30, verbose_name='横轴标签')),
                ('ylabel', models.CharField(default='', help_text='Y轴标签', max_length=30, verbose_name='纵轴标签')),
                ('mth_power', models.IntegerField(default=1, verbose_name='次数m')),
                ('error_type', models.IntegerField(choices=[(1, 'MSE: 均方误差'), (2, 'MAE: 平均绝对误差'), (3, 'RMSE: 均方根误差'), (4, 'R2: R平方值')], help_text='默认MSE', verbose_name='误差计算类别')),
                ('chart_folder1', models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='图表存放路径1')),
                ('chart_folder2', models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='图表存放路径2')),
                ('chart_folder3', models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='图表存放路径3')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('updated_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='更新时间')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='data_mining.ModelCategory', verbose_name='模型类目')),
            ],
            options={
                'verbose_name': '回归分析模型',
                'verbose_name_plural': '回归分析模型',
            },
        ),
    ]
