# Generated by Django 2.0.4 on 2018-09-20 08:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data_mining', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='regression',
            options={'verbose_name': '回归分析模型', 'verbose_name_plural': '回归分析模型'},
        ),
        migrations.AlterField(
            model_name='regression',
            name='data_set',
            field=models.IntegerField(default=-1, verbose_name='数据集ID'),
        ),
        migrations.AlterField(
            model_name='regression',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户ID'),
        ),
    ]
