# Generated by Django 2.0.4 on 2018-09-20 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_mining', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='regression',
            name='category',
        ),
    ]
