# Generated by Django 2.0 on 2018-11-15 10:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('data_mining', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='regression',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户ID'),
        ),
        migrations.AddField(
            model_name='modelcategory',
            name='parent_category',
            field=models.ForeignKey(blank=True, help_text='父目录', null=True, on_delete=True, related_name='sub_cat', to='data_mining.ModelCategory', verbose_name='父类目级别'),
        ),
        migrations.AddField(
            model_name='clustering',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='data_mining.ModelCategory', verbose_name='模型类目'),
        ),
        migrations.AddField(
            model_name='clustering',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户ID'),
        ),
    ]
