# Generated by Django 2.0.4 on 2018-09-20 08:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data_mining', '0002_remove_regression_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='regression',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='data_mining.ModelCategory', verbose_name='模型类目'),
        ),
    ]
