# Generated by Django 2.0.4 on 2018-09-21 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_mining', '0003_regression_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='regression',
            name='xlabel',
            field=models.CharField(default='', help_text='X轴标签', max_length=30, verbose_name='横轴标签'),
        ),
        migrations.AddField(
            model_name='regression',
            name='ylabel',
            field=models.CharField(default='', help_text='Y轴标签', max_length=30, verbose_name='纵轴标签'),
        ),
    ]
