# Generated by Django 2.0.4 on 2018-09-25 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_mining', '0004_auto_20180921_0320'),
    ]

    operations = [
        migrations.RenameField(
            model_name='regression',
            old_name='division_ratio',
            new_name='test_size',
        ),
    ]
