# Generated by Django 2.0 on 2018-11-15 10:44

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shared_user', models.IntegerField(null=True, verbose_name='被分享者用户')),
                ('task', models.IntegerField(blank=True, help_text='分享后的任务id', null=True, verbose_name='分享后的任务id')),
                ('task_name', models.CharField(blank=True, help_text='分享任务名', max_length=80, null=True, verbose_name='分享任务名')),
                ('add_time', models.DateTimeField(blank=True, default=datetime.datetime.now, null=True, verbose_name='添加时间')),
                ('update_time', models.DateTimeField(blank=True, default=datetime.datetime.now, null=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '发布',
                'verbose_name_plural': '发布',
            },
        ),
        migrations.CreateModel(
            name='Summary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataAnalyze_Summary', models.CharField(blank=True, max_length=80, null=True, verbose_name='数据分析结论')),
                ('dataMining_Summary', models.CharField(blank=True, max_length=80, null=True, verbose_name='数据挖掘结论')),
                ('total_Summary', models.CharField(blank=True, max_length=80, null=True, verbose_name='任务总结')),
                ('html_folder', models.CharField(max_length=80, null=True, verbose_name='html地址')),
                ('add_time', models.DateTimeField(blank=True, default=datetime.datetime.now, null=True, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '总结',
                'verbose_name_plural': '总结',
            },
        ),
        migrations.CreateModel(
            name='UserTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('tasks', models.ForeignKey(help_text='任务id', on_delete=django.db.models.deletion.CASCADE, to='tasks.TaskInfo', verbose_name='任务')),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户',
            },
        ),
    ]
