# Generated by Django 2.0 on 2018-11-15 10:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_operation', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tasks', '0002_auto_20181115_1044'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertask',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
        migrations.AddField(
            model_name='summary',
            name='task',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='task_S', to='tasks.TaskInfo', verbose_name='任务id'),
        ),
        migrations.AddField(
            model_name='summary',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_S', to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
        migrations.AddField(
            model_name='publish',
            name='source_task',
            field=models.ForeignKey(help_text='源任务id', on_delete=django.db.models.deletion.CASCADE, to='tasks.TaskInfo', verbose_name='源任务'),
        ),
        migrations.AddField(
            model_name='publish',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL, verbose_name='分享者用户'),
        ),
        migrations.AlterUniqueTogether(
            name='usertask',
            unique_together={('user', 'tasks')},
        ),
        migrations.AlterUniqueTogether(
            name='publish',
            unique_together={('user', 'task_name')},
        ),
    ]
